name: generative_ai_repository
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  langchain: ^0.0.8
  langchain_openai: ^0.0.8+1

dev_dependencies:
  very_good_analysis: ^5.0.0+1
  test: ^1.21.0
