name: authentication_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  fpdart: ^1.1.0
  supabase: ^1.11.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1
  test: ^1.21.0
