name: app
description: Forntend of the app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:

  walletconnect_flutter_v2: ^2.1.4
  walletconnect_modal_flutter: ^2.1.0
  # Analytics

  # Animation

  # Client
  speech_to_text: ^6.3.0
  flutter_tts: ^3.7.0

   # Crash Reporting

  # Database

  # Dependency Injection
  get_it: ^7.6.0

  # Design
  flutter_screenutil: ^5.8.4

  # Foundation
  flutter:
    sdk: flutter

  # Localization

  # Logging
  talker_bloc_logger: ^2.2.0
  talker_flutter: ^3.2.9

  # Model
  freezed_annotation: ^2.4.1

  # Navigation
  auto_route: ^7.8.0

  # Network

  # Performance

  # Repository
  generative_ai_repository:
  web3_repository:

  
  # Security

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  # Storage

  # UI
  app_ui:
  cupertino_icons: ^1.0.2
  flutter_iconly: ^1.0.2

  # Utility
  form_inputs:


  wc_web3_authentication_client:

dev_dependencies:
  # Code Quality
  very_good_analysis: ^5.0.0+1

  # Code Generation
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.2

  # Testing
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
