name: wc_web3_authentication_client
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  walletconnect_modal_flutter: ^2.1.0
  webthree: ^2.5.7+2
  walletconnect_flutter_v2: ^2.1.4
  equatable: ^2.0.5
  fpdart: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
