name: web3_authentication_client
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
